aws_region: "us-east-1"

services:
  ecs:
    ecs_cluster_name: "my-ecs-cluster"
    ami: "ami-0b0ea68c435eb488d"
    ecs_instance_type: "t3.medium"
    subnet_ids: "subnet-0cca8fd4378a176ff"

  s3:
    bucket_name: "my-app-bucket"
  iam:
    roles:
      - name: "AppAdminRole"
        policies:
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      - name: "ReadOnlyRole"
        policies:
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"
    groups:
      - name: "AdminGroup"
        policies:
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      - name: "ReadOnlyGroup"
        policies:
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"

  vpc:
    cidr: "10.0.0.0/16"
    public_subnet_cidr: "10.0.1.0/24"
    availability_zone: "us-east-1a"

  ec2:
    instance_type: "t2.micro"
    ami_id: "ami-0b0ea68c435eb488d"
    key_name: "my-key-pair"