aws_region: "us-east-1"

services:
  ecs:
    cluster_name: "my-ecs-cluster"
    service_name: "my-service"
    execution_role_arn: "arn:aws:iam::724772050207:role/ECSTaskExecutionRole"
    task_role_arn      : "arn:aws:iam::724772050207:role/ECSTaskExecutionRole"
    ecs_security_groups : ["sg-0a4944f656ab9eb44"]
    subnet_ids         : ["subnet-0cca8fd4378a176ff"]
    vpc_id             : "vpc-0e88381e6c4aa04f8"
    container_name     : "my-container"
    container_port: 80
    desired_count : 1

  s3:
    bucket_name: "my-app-bucket"
  iam:
    roles:
      - name: "AppAdminRole"
        policies:
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      - name: "ReadOnlyRole"
        policies:
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"
    groups:
      - name: "AdminGroup"
        policies:
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      - name: "ReadOnlyGroup"
        policies:
          - "arn:aws:iam::aws:policy/ReadOnlyAccess"

  vpc:
    cidr: "10.0.0.0/16"
    public_subnet_cidr: "10.0.1.0/24"
    availability_zone: "us-east-1a"

  ec2:
    instance_type: "t2.micro"
    ami_id: "ami-0b0ea68c435eb488d"
    instance_count: 3
    instance_name: "my-ec2-instance"


  iam_user_creation:
    policy_name: "AdministratorAccess"
    user_prefix: "my-admin-user"